services:
  - type: web
    name: eventos-backend
    env: node
    plan: free
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eventos-db
          property: connectionString

databases:
  - name: eventos-db
    plan: free
